coverage:
  status:
    patch:
      default:
        target: 80%        # Minimum threshold
        threshold: 0%    # Allowed drop before failing
        if_not_found: failure
        informational: false
        base: parent

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

