coverage:
  status:
    patch: true

  range: 85..90     # First number represents red, and second represents green
                    # (default is 70..100)
  round: down       # up, down, or nearest
  precision: 2

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

